### ISSUE TITLE
Download links do not work

### ISSUE THREAD

**Issue by aweers** [pyt-team/tdlbook#3]
Great project! Thanks for the effort, looking forward to reading it. 

However, both download links (pdf and epub) do not work, i. e. result in a "Page not found".

**Comment by papamarkou** [comment]
Thank you for pointing this out, @aweers! The plan is for the book to be published as well with a publisher (as a hard copy), and for this reason we have been planning to maintain the web book only over the web. Your remark is legit, we need to then ensure that there are no links for pdf or epub.

**Comment by papamarkou** [comment]
@aweers I fixed this by hiding the download button, thank you for bringing this to my attention!
